# Generated by Django 5.0.1 on 2024-02-02 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(upload_to='media/profile_pictures/'),
        ),
    ]
